### ISSUE TITLE
python server.py -d 3ng -j static/3ng.json

### ISSUE THREAD

**Issue by EasonZhaoZ** [marcotcr/mlforhumans#1]
Traceback (most recent call last):
  File "server.py", line 1, in ?
    import bottle
  File "/home/zhaoyin.zy/mlforhumans/bottle.py", line 141
    return s.encode(enc) if isinstance(s, unicode) else bytes(s)
                          ^
SyntaxError: invalid syntax

**Comment by EasonZhaoZ** [comment]
how to fix this error?

**Comment by marcotcr** [comment]
I suspect you are using an older version of python. Try using 2.7 at least.

**Comment by EasonZhaoZ** [comment]
python server.py -d 3ng -j static/3ng.json


Traceback (most recent call last):
  File "server.py", line 10, in <module>
    from sklearn.datasets import fetch_20newsgroups
ImportError: No module named sklearn.datasets


another error. ..

**Comment by marcotcr** [comment]
You need to have scikit-learn installed if you are to run the server that uses scikit-learn.
I have yet to set the dependencies and provide a how-to run the project.
This project is not ready for public consumption yet.
